development:
  adapter: mysql
  database: phd_development
  username: phd_development
  password: phd_development

test:
  adapter: mysql
  database: phd_test
  username: phd_test
  password: phd_test

# production:
#   adapter: sqlite3
#   database: db/production.sqlite3
#   pool: 5
#   timeout: 5000
