development:
  adapter: mysql
  database: phd_development
  username: phd_development
  password: phd_development

test:
  adapter: mysql
  database: phd_test
  username: phd_test
  password: phd_test

production:
  adapter: mysql
  database: phdproject
  username: phdproject
  password: phdproject
